# Lab 3: NumPy Basics
## (Intro)
This notebook covers basic NumPy concepts.

## What is NumPy?
NumPy is a Python library used for numerical operations.
It is faster than lists and useful for arrays and mathematical work.

## Importing NumPy

In [1]:
import numpy as np

print('NumPy imported')

NumPy imported


## Creating Arrays

In [2]:
# 1D array
arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


In [3]:
# 2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


## Array Properties

In [4]:
print(arr2.shape)   # rows and columns
print(arr2.ndim)    # dimension
print(arr2.size)    # total elements

(2, 3)
2
6


## Special Arrays

## Using arange()

In [5]:
x = np.arange(0,10,2)
print(x)

[0 2 4 6 8]


## Basic Operations

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


## Indexing

In [6]:
arr = np.array([10,20,30,40])
print(arr[0])
print(arr[2])

10
30


## Reshape

In [8]:
arr = np.array([1,2,3,4,5,6])
new_arr = arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]
